### PR TITLE
Created a Markdown Readme

### PR DESCRIPTION
**Pull request by zenware**
Resolves issue shmup/wander#1

### CODE REVIEW

**Comment by shmup** [comment]
Whoops. Didn't mean to leave Travis toggled on.

Thanks for taking the time to do this. I've had second thoughts on it, but I think we should use some of it. Don't really know if the whole thing makes sense to put in a README.

I'm in the processes of creating a wander.1 for man to parse, which'll just be a 1:1 of wander.nr

**Comment by zenware** [comment]
Yeah, I didn't think it all made sense but it was quickest and easiest for me to copy all of it and use some Regular Expressions to change the formatting.

**Comment by shmup** [comment]
Here's what I'm thinking..

I like the idea of explaining Wander more historically like the current README does, giving some useful links for additional reading etc.

But maybe beneath that we do a segment of the man page, using what you did from just START to DESCRIPTION. Sorry for the work you put into the rest if we go this route. :P

Maybe also saying to read the full manual you can:

`man ./wander.1` or `nroff ./wander.nr | less`

What do you think?

**Comment by zenware** [comment]
@shmup That sounds nice, I can poke around on some of the blog stuff and write some more historical copy. I'm thinking I can include information like what other "games"(non default worlds) were made with wander, and the implementation history. If there's anything specific you want added you should mention it.

**Review by shmup — APPROVED** [review]

**Pull request merged**
